TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += sr850.db
DATA += sr850.proto

#=======================================
include $(TOP)/configure/RULES
